# WorldParameters:
carla_timeout: 9.0
map_name: Town05
actor_active_distance: 100
hybrid_physics_radius: 30
tile_stream_distance: 100
# TrafficParameters:
num_vehicles: 100
spwan_points_distance: 20
area_limit:
  min_x: -500
  max_x: 5000
  min_y: -500
  max_y: 4000
# DebugParameters:
camera_height: 60
debug_sp: False

# agents:
agents:
  - name: "agent1"
    port: 9561
    type: "vehicle.ford.crown"
    start_point: 136
    end_point: 251
    # end_point: 6
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent2"
    port: 9562
    type: "vehicle.ford.crown"
    start_point: 135
    end_point: 174
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent3"
    port: 9563
    type: "vehicle.ford.crown"
    start_point: 173
    end_point: 60
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent4"
    port: 9564
    type: "vehicle.ford.crown"
    start_point: 176
    end_point: 60
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent5"
    port: 9565
    type: "vehicle.ford.crown"
    start_point: 295
    end_point: 109
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent6"
    port: 9566
    type: "vehicle.ford.crown"
    start_point: 294
    end_point: 108
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent7"
    port: 9567
    type: "vehicle.ford.crown"
    start_point: 153
    end_point: 289
    main_port: 6000
    traffic_agent_port: 9555
  - name: "agent8"
    port: 9568
    type: "vehicle.ford.crown"
    start_point: 154
    end_point: 231
    main_port: 6000
    traffic_agent_port: 9555